.TH lar 1
.SH NAME
lar \- lock archive and run ar.
.SH SYNOPSIS
.B lar
[\fIOPTION\fR]... \fIarchive\fR [\fImember\fR]...
.SH DESCRIPTION
.B lar
locks the lock file for \fIarchive\fR and executes \fIar\fR with \fIOPTION\fRs, \fIarchive\fR and \fImember\fRs.
The name of the lock file is created by removing a \fB.a\fR suffix from \fIarchive\fR if present, and appending a \fB.lock\fR suffix.
.SH AUTHOR
Written by Christian Hujer.
.SH REPORTING BUGS
Report bugs via <https://github.com/christianhujer/lar/issues>
.SH COPYRIGHT
Copyright © 2015 Chrsitian Hujer.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
